# Generated by Django 3.2.8 on 2021-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, max_length=200, unique=True, upload_to=''),
            preserve_default=False,
        ),
    ]
